name: phpunit

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          version: 9.6.4
          args: --coverage-text